// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TriviaPvPCoreAPI.DTO;

public partial class GameSession
{
    public Guid SessionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<TriviaQuestion> TriviaQuestions { get; set; } = new List<TriviaQuestion>();

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();
}