// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TriviaPvPCoreAPI.DTO;

public partial class Player
{
    public int PlayerId { get; set; }

    public string PlayerName { get; set; }

    public int? Score { get; set; }

    public bool? Answered { get; set; }

    public virtual ICollection<GameSession> Sessions { get; set; } = new List<GameSession>();
}