// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TriviaPvPCoreAPI.DTO;

public partial class TriviaQuestionOption
{
    public int OptionId { get; set; }

    public int? QuestionId { get; set; }

    public string OptionText { get; set; }

    public virtual TriviaQuestion Question { get; set; }
}