// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TriviaPvPCoreAPI.DTO;

public partial class TriviaQuestion
{
    public int QuestionId { get; set; }

    public string Question { get; set; }

    public string CorrectAnswer { get; set; }

    public Guid SessionId { get; set; }

    [JsonIgnore]
    public virtual GameSession Session { get; set; }
    [JsonIgnore]
    public virtual ICollection<TriviaQuestionOption> TriviaQuestionOptions { get; set; } = new List<TriviaQuestionOption>();
}