// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TriviaPvPCoreAPI.DTO;

public partial class TriviaContext : DbContext
{
    public TriviaContext(DbContextOptions<TriviaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GameSession> GameSessions { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<TriviaQuestion> TriviaQuestions { get; set; }

    public virtual DbSet<TriviaQuestionOption> TriviaQuestionOptions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GameSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__GameSess__C9F49290DF923FEA");

            entity.Property(e => e.SessionId).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.PlayerId).HasName("PK__Players__4A4E74C8DA402631");

            entity.Property(e => e.Answered).HasDefaultValue(false);
            entity.Property(e => e.PlayerName).HasMaxLength(100);
            entity.Property(e => e.Score).HasDefaultValue(0);

            entity.HasMany(d => d.Sessions).WithMany(p => p.Players)
                .UsingEntity<Dictionary<string, object>>(
                    "PlayerGameSession",
                    r => r.HasOne<GameSession>().WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__PlayerGam__Sessi__4CA06362"),
                    l => l.HasOne<Player>().WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__PlayerGam__Playe__4BAC3F29"),
                    j =>
                    {
                        j.HasKey("PlayerId", "SessionId").HasName("PK__PlayerGa__56D13DE1BF647CDC");
                        j.ToTable("PlayerGameSession");
                    });
        });

        modelBuilder.Entity<TriviaQuestion>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("PK__TriviaQu__0DC06FAC55D05D98");

            entity.Property(e => e.CorrectAnswer)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Question).IsRequired();

            entity.HasOne(d => d.Session).WithMany(p => p.TriviaQuestions)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_TriviaQuestion_GameSession");
        });

        modelBuilder.Entity<TriviaQuestionOption>(entity =>
        {
            entity.HasKey(e => e.OptionId).HasName("PK__TriviaQu__92C7A1FFC09C066E");

            entity.Property(e => e.OptionText).HasMaxLength(255);

            entity.HasOne(d => d.Question).WithMany(p => p.TriviaQuestionOptions)
                .HasForeignKey(d => d.QuestionId)
                .HasConstraintName("FK__TriviaQue__Quest__52593CB8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}